module.exports = {
  RET_SUCCESS:0,
  RET_ERROR:-1,
  LOBBY:{
    FIRST_LOGIN_AWARD_GOLD:1000,
    EVERYDAY_LOGIN_AWARD_GOLD:100,
    FOREVER_TIME:365*24*100,//100年
    eLoginType:{
      LOGIN_TYPE_YK:1,
      LOGIN_TYPE_QQ:2,
      LOGIN_TYPE_WX:3
    },
    eClientType:{
      CLIENT_TYPE_IPHONE:1,
      CLIENT_TYPE_IPAD:2,
      CLIENT_TYPE_ANDROID:3,
      CLIENT_TYPE_PC:4
    },
    eNetWorkType:{
      NETWORK_TYPE_WIFI:1,
      NETWORK_TYPE_4G:2
    },
    eLoginResultFlag:{
      LOGIN_SUCCESS:0,
      LOGIN_FAIL_INCORRECT_PWD:1,
      LOGIN_FAIL_NOT_EXIST_ACCOUT:2,
      LOGIN_FAIL_NOT_SUPPORT_TYPE:3,
      LOGIN_FAIL_OPENID_ERROR:4,
      LOGIN_SUCCESS_HAS_LOGIN:5
    },
    eChangeNameFlag:{
      CHANGE_SUCCESS:1,//成功
      CHANGE_FAIL_FOR_EXIST:2,//已经存在
      CHANGE_FAIL_INVLID:3//不合法
    },
    SERVER_STATE:{
      SERVER_STATE_NOT_AVAILABLE:0,
      SERVER_STATE_IDLE:1,
      SERVER_STATE_CROWD:2,
      SERVER_STATE_FULL:3
    },
    LMT_TYPE:{
      LMT_BY_NONE:0,
      LMT_BY_GOLD:1,
      LMT_BY_LEVEL:2
    },
    PROP_TYPE:{
      PROP:1,
      SKIN:2,
      HERO:3
    },
    SYS_OR_PRIVATE_MSG_TYPE:{
      TYPE_MSG_SYS:0,
      TYPE_MSG_PRIVATE:1,
      TYPE_MSG_NOTICE:2
    },
    RANK_SCOPE_TYPE:{
      RANK_ALL:0,
      RANK_FRIEND:1,
      RANK_AREA:2
    },
    RANK_TYPE:{
      RANK_GOLD:0,//财富
      RANK_CHARM:1,//魅力
      RANK_DIAMOND:2,//钻石
      RANK_SCORE:3,//积分
      RANK_WINRATE:4//胜率
    },
    SIGNIN_FLAG:{
      SIGNIN_FLAG_SUCESS:0,
      SIGNIN_FLAG_HAS_SIGNIN:1,
      SIGNIN_FLAG_INVLID:2
    },
    RESP_JOINROOM_FLAG:{
      JOINROOM_SUCCESS:0,
      JOINROOM_GOLD_LESS:1,
      JOINROOM_GOLD_MORE:2,
      JOINROOM_LEVEL_LESS:3,
      JOINROOM_LEVEL_MORE:4,
      JOINROOM_NO_ROOMID:5
    },
    LEAVE_TYPE:{
      LEVEL_TYEP_NORMAL:0,
      LEVEL_TYPE_KICK:1,
      LEVEL_TYPE_ESCAPE:2
    },
    eReqUpdateEmailActionType:{
      READ:0,
      DEL:1,
      GET_AWARD:2,//READ AND GET
    },
    eAwardType:{
      NONE:0,
      GOLD:1,
      PROP:2
    },
    eFeedbackType:{
      BUG:0,
      ACCOUNT:1,
      AWARD:2,
      RECHARGE:3,
      SUGGEST:4,
      DANMU:5
    },
    eOpenByType:{
      OPEN_BY_GOLD:0,
      OPEN_BY_DIAMOND:1,
    },
    eOpenTalentslotResult:{
      OPEN_SUCCESS:0,
      OPEN_FAIL:1,//
      OPEN_FAIL_LESS_GOLG:2,
      OPEN_FAIL_LESS_DIAMOND:3,
      OPEN_FAIL_MAX_SLOT:4,//达到最大槽数，即已经全打开过了，属于非法操作
    },
    eOpenTalentslotNeed:{
      NEED_GOLD:1000,
      NEED_DIAMOND:50,
    },
    MAX_TALENT_SLOT:4,
  },
  ROOM:{
    ROOM_ID_INVLID :0,
    ROOM_ID_BEGIN:100001,
    ROOM_ID_END  :999999,
    ROOM_INVLID_SEAT:255,
    ROOM_MAX_WAIT_TIME:20,//单位分钟，最多等待20分钟
    ROOM_MAX_EXIST_TIME:1440,// 最长存在一天
    ROOM_TYPE:{
      ROOM_CLASSIC_PLAZA:0,//默认固定的经典模式，即主大厅直接开始的模式
      ROOM_PLAZA:1,//系统房间，即场模式房间
      ROOM_ROOM:2,//用户创建房间
      ROOM_TEAM:3,//队伍房间，即队伍模式
    },
    PLAZA_ROOM_LEVEL:{
      PLAZA_LEVEL_LOW:1,
      PLAZA_LEVEL_MIDDLE:2,
      PLAZA_LEVEL_HIGH:3
    },
    ROOM_GAME_STATE:{
      ROOM_INVILD:0,
      ROOM_WAIT:1,
      ROOM_PLAYING:2
    },
    JOIN_ROOM_RESULT:{
      JOINROOM_SUCCESS:0,
      JOINGROOM_FAIL_ROOM_NOT_EXIST:1,
      JOINROOM_FAIL_NO_FREE_ROOM:2,
      JOINROOM_GOLD_LESS:3,//金币不足
      JOINROOM_GOLD_MORE:4,//金币过高
      JOINROOM_LEVEL_LESS:5,//等级过低
      JOINROOM_LEVEL_MORE:6,//等级过高
      JOINROOM_PWD_ERR:7,//密码错误
      JOINROOM_ACCOUNT_ERR:8,//用户不存在
      JOINROOM_PLAZA_ERR:9,//所选择的场不存在
      JOINGROOM_ALREADY_IN_ROOM:10,//已经在房间中
      JOINROOM_FIAL_SYSERR:11//系统出错
    },
    STATE_TYPE:{
      STATE_TYPE_NONE:0,//无效状态
      STATE_TYPE_STANDUP:1,//站起//因为不支持table模式，所以默认都是坐下的
      STATE_TYPE_SITDOWN:2,//坐下
      STATE_TYPE_ROOMREADY:3,//准备中
      STATE_TYPE_PLAYING:4,//游戏中
      STATE_TYPE_OFFLINE:5,//离线
      STATE_TYPE_SEEING:6//观战
    },
    PLAYER_ACT:{
      ACT_SITDOWN:0,//坐下，之后才能准备
      ACT_STANDUP:1,//站起
      ACT_READY:2,//准备
      ACT_SEEING:3//旁观
    },
    PLAYER_LEAVE:{
        LEAVE_NORMAL:0,//正常离开
        LEAVE_KICK:1,//被t
        LEAVE_ESCAPE:2,//逃跑
        LEAVE_NOT_IN_ROOM:3,//不在房间中
        LEAVE_CANT_LEAVE:4,//不能离开
        LEAVE_DISSOLVE:5//解散
    },
    ROOMSTATE_CHANGE_TYPE:{
      ROOMSATE_NONE:0,
      ROOMSTATE_ADD:1,
      ROOMSTATE_REMOVE:2,
      ROOMSTATE_UPDATE:3
    },
    PLAYER_LEAVE_ROOM_TYPE:{
      LEAVE_ROOM_NORMAL:0,//正常退出
      LEAVE_ROOM_WAIT_TIMEOUT:1,//等待游戏开始时间过长
      LEAVE_ROOM_EXIST_TIMEOUT:2,//超出最长房间占用时间
      LEAVE_ROOM_OWNER_OFFLINE:3,//房主掉线
      LEAVE_ROOM_OWNER_DISSOLVE:4,//房主解散房间
      LEAVE_ROOM_GAMEEND:5//游戏结束
    },
    eTalentType:{
      TALENT_NONE:0,
      TALENT_A1:1,//资源占据：从自己所在格子获得1生命点
      TALENT_A2:2,//a2资源吸收：从前后未被敌人占据的格子各获得1生命点
      TALENT_A3:3,//a3基本攻击：面向敌人，以1点攻击力攻击前方敌人
      TALENT_B1:4,// b1加命：面对友军，为友军增加1生命点；
      TALENT_B2:5,//b2助攻：面对友军，且友军处于攻击状态，则自己的攻击力加到友军身上；备注：妨碍敌方的a2天赋可以减少敌方生命总量；背对背是天赋b5处于攻击状态= 面对敌人或面对空格
      TALENT_B3:6,//b3环：己方n个棋子形成环，每个棋子增加n生命点
      TALENT_B4:6,// b4吸收：两个棋子相对，各具备3吸收力，能够对背后的敌人吸收最多3的攻击力；备注：经最近测试，改为3吸收力可以让吸收阵更加实用，而且也不会过于强大，不过可能导致以前设计的一些残局解法有变，一个有效的解决办法就是给以往的残局再设定天赋条件，比如每个残局都设定好了允许使用的天赋
      TALENT_B5:7,//b5双尖：两颗棋子背对背，各增加2攻击力；
      TALENT_C1:8// c1吃子移动：己方活动时，若通过攻击干掉对方棋子，则获得1点移动能力，允许在本回合内向前移1格；
    }
  },
  GAME:{
    TIME:{
    },
    GAME_STEP:{
      GAME_STEP_NONE:0,//空状态
      GAME_STEP_START:1,//对局开始
      GAME_STEP_DICE:2,//掷骰子
      GAME_STEP_PLAY:3,//落子阶段
      GAME_STEP_MOVE_OR_PASS:4,
      GAME_STEP_MOVE:5,//移动阶段
      GAME_STEP_PASS:6,//回合结束阶段
      GAME_STEP_ABANDON:7,//投降阶段
      GAME_STEP_DRAW:8,//请和阶段
      GAME_STEP_END:9//结束
    },
    GAME_DIRECT_TYPE:{
      LIANQI_DIRECTION_TYPE_NONE:-1,//不使用禁止方向
      LIANQI_DIRECTION_TYPE_0:0,
      LIANQI_DIRECTION_TYPE_1:1,
      LIANQI_DIRECTION_TYPE_2:2,
      LIANQI_DIRECTION_TYPE_3:3,
      LIANQI_DIRECTION_TYPE_4:4,
      LIANQI_DIRECTION_TYPE_5:5
    },
    GAME_OP_RESP_FLAG:{
      SUCCESS:0,//成功
      SEAT_ERR:1,//座位号错误
      ILLEGAL:2,//非法操作
      INCORRECT_TURN:3,//不正确的出子方
      NOT_IN_GAME:4, //根本不在游戏中
      INCORRECT_STEP:5,//游戏步骤不正确
    },

    NOTIFY_GAME_STATE:{
      NONE:0,
      START:1,
      PLAY:2,
      MOVE:3,
      DRAW:4,
      PASS:5,
      ABANDON:6,
      RELINK:7,
      END:8
    },
    GAME_FLAG:{
      RELINK_TYPE_BEGIN:0,
      RELINK_TYPE_END:1,
    }
  }
};

